version: '3'

services:

  mysql:
    container_name: 'shorturl-mysql'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_USERNAME: 'root'
    ports:
      - '3306:3306'

  redis:
    container_name: 'shorturl-redis'
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: 'root'
      REDIS_USERNAME: 'root'
    ports:
      - '6379:6379'

  shorturl:
    container_name: 'shorturl'
    build:
      context: ..
      dockerfile: DockerFiles/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - mysql