ENV: dev

HOST: 'localhost'
PORT: 8000
RELOAD: true

SECRET_KEY: 'secret_key'

DB:
  HOST: 'localhost'
  PORT: 3306
  USERNAME: 'root'
  PASSWORD: 'root'
  DATABASE: 'shorturl'

REDIS:
  HOST: 'localhost'
  PORT: 6379
  PASSWORD: 'root'
  DATABASE: 0